name: cbtapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.2.5+1

environment:
  sdk: ^3.5.3

dependencies:
  connectivity_plus: ^6.1.3
  device_info_plus: ^11.1.1
  flutter:
    sdk: flutter
  package_info_plus: ^8.3.0
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
